 name: CI/CD Pipeline

 on:
  push:
    branches:
      - main

 jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install ArgoCD CLI
        run: |
          curl -LO https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
          chmod +x argocd-linux-amd64
          sudo mv argocd-linux-amd64 /usr/local/bin/argocd

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Deploy
        run: |
          # Add build or processing steps here if needed
          echo "Build and processing steps"

          # Deploy to ArgoCD
          argocd login localhost:8080 --username admin --password YMBhHfLWGYJvBsDD --insecure
          argocd app set SPARK-APP -p default --sync-policy auto
          argocd app sync SPARK-APP


