name: Deploy to ArgoCD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy to ArgoCD
        run: |
          cd custom-folder  # Navigate to the custom folder
          # Perform any deployment actions needed for this folder
