 name: Spark CI

on:
  push:
    branches:
      - main

jobs:
  build:
    # runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Spark App
        run: |
          cd custom_folder
          # Replace this with your actual build commands
          # Example: ./build.sh
